language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean install sonar:sonar -Dsonar.host.url=https:/sonarqube.com -Dsonar.login=${27745073c9620192a328e02f0d73ce5ca24f1ca5}

  
  
